[package]
authors = ["Michael Rutter <michael.john.rutter@gmail.com>"]
edition = "2018"
name = "aoc-2017"
version = "0.1.0"

[lib]
name = "aoc_2017"
path = "src/lib.rs"

[[bin]]
name = "aoc-cli"

[dependencies]
clap = "2.32.0"
failure = "0.1.3"
itertools = "0.7.8"
