[package]
authors = ["Michael Rutter <michael.john.rutter@gmail.com>"]
edition = "2018"
name = "aoc-2017"
version = "0.1.0"
[dependencies]
clap = "*"
failure = "*"
itertools = "*"

[[bin]]
name = "aoc-cli"