[package]
authors = ["Michael Rutter <michael.john.rutter@gmail.com>"]
edition = "2018"
name = "advent_of_code"
version = "0.1.0"

[lib]
name = "advent_of_code"
path = "src/lib.rs"

[[bin]]
name = "aoc-cli"

[dependencies]
clap = "2.32.0"
failure = "0.1.3"
itertools = "0.7.11"
pest = "2.0.2"
pest_derive = "2.0.1"
